# https://answers.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759/17
[build.environment]
  NPM_FLAGS = "--version"

[build]
  publish = "dist"
  command = """
    PNPM_VERSION=$(node -p -e "require('./package.json').devDependencies.pnpm")
    npx pnpm@${PNPM_VERSION} i --frozen-lockfile &&
    npx pnpm@${PNPM_VERSION} build
  """
